### PR TITLE
code page and thumbnail fix

### PR DESCRIPTION
**Pull request by IamShubhamGupto**
- included all models, tutorials, datasets and parameterizations from #55 (manually, will work on finishing the script next)
- fixed misplaced thumbnail for publication as mentioned in first point of #54 
- reused dynamic keywords template from team members site for tags

Screenshot 2023-09-04 at 8 05 24 PM

### CODE REVIEW

**Comment by NoraLoose** [comment]
Thanks for this PR @IamShubhamGupto - awesome progress!

IMO it would look more organized if we could somehow keep the structure that I suggested in #55. I.e., sections like "Machine learning tutorials and tools" and then have the associated items in that section.

Also, where does the link take you when you for example click on "Differentiable QG Model"? I think it could be nice to have several links per item, as I suggested in #55. For example, "Differentiable QG Model" could have a link to the actual code, and another one to the paper.

**Comment by IamShubhamGupto** [comment]
> Thanks for this PR @IamShubhamGupto - awesome progress!
> 
> IMO it would look more organized if we could somehow keep the structure that I suggested in #55. I.e., sections like "Machine learning tutorials and tools" and then have the associated items in that section.
> 
> Also, where does the link take you when you for example click on "Differentiable QG Model"? I think it could be nice to have several links per item, as I suggested in #55. For example, "Differentiable QG Model" could have a link to the actual code, and another one to the paper.

Could you finalize the other in which I should display the content, I feel dataset and tutorial have less content so they should come below

as for the links, the titles point to the paper itself. The tags `website` `code` and `dataset used` point to those individual links respectively.

**Comment by IamShubhamGupto** [comment]
@NoraLoose 

I was able to add divisions to the code, the results

Screenshot 2023-09-04 at 9 58 46 PM

Screenshot 2023-09-04 at 9 58 54 PM


Let me know if I should push these

**Comment by NoraLoose** [comment]
@IamShubhamGupto I like that better, thanks! I will shorten some of the names in #55, and let you know when it's updated.

**Comment by NoraLoose** [comment]
I will merge this PR for now, so it is easier for us to look at the result. (I don't have the local build set up right now.) Let's then make suggestions in a follow-up PR. @johannag126 could maybe help, too, if she has time.

**Review by NoraLoose — APPROVED** [review]

**Comment by NoraLoose** [comment]
@IamShubhamGupto  List updated (just shortened GCM-Filters and some items in the atmospheric parameterization section).

**Comment by IamShubhamGupto** [comment]
> @IamShubhamGupto List updated (just shortened GCM-Filters and some items in the atmospheric parameterization section).

no problem, the new design and updated titles will be in the next pr, shouldn't take long

**Pull request merged**
